Train:
    trainFile : "/workspace/mnt/group/general-reg/mayufeng/github/Atlab-myf/pytorch-tool/blade_train_exd_tq5-10.lst"
    valFile : "/workspace/mnt/group/general-reg/mayufeng/github/Atlab-myf/pytorch-tool/blade-val-labeled.lst"
    epoch : 100
    model_name : se_resnext50_32x4d
    num_classes: 3
    batch_size: 128
    feature_extract: False
    savePath: '/workspace/mnt/group/general-reg/mayufeng/github/Atlab-myf/pytorch-tool/model/ss_50/se_resnext50_32x4d_tq5-10_sgd_re'
    lr: 0.01 
    momentum: 0.9 
    mean: [0.485, 0.456, 0.406] 
    std: [0.229, 0.224, 0.225]
    loadPt: 
    start_epoch: 0 
    pretrain : True
    optim : sgd
