Train:
    trainFile : ".lst"
    valFile : ".lst"
    epoch : 80
    model_name : resnet
    num_classes: 3
    batch_size: das
    feature_extract: True
    savePath: 'model/resnet-18'
    lr: 
    momentum: 
    mean: [0.485, 0.456, 0.406] 
    std: [0.229, 0.224, 0.225]
#    loadPt : 